// src/shared/courseData.js
export const COURSES = [
  {
    id: "c01",
    title: "인류학의 이해",
    teacher: "김○○",
    uni: "전북대학교",
    weeks: 14,
    learners: "12.4만",
    rating: 4.6,
    badge: "입문",
    thumb: "seed",
    slug: "anthropology-basics",
  },
  {
    id: "c02",
    title: "파이썬으로 데이터 과학",
    teacher: "박○○",
    uni: "부산대학교",
    weeks: 14,
    learners: "12.4만",
    rating: 4.6,
    badge: "데이터",
    thumb: "data",
    slug: "python-data-science",
  },
  {
    id: "c03",
    title: "리액트 고급 개발",
    teacher: "이○○",
    uni: "서울대학교",
    weeks: 14,
    learners: "12.4만",
    rating: 4.6,
    badge: "프로젝트",
    thumb: "react",
    slug: "react-advanced",
  },
  {
    id: "c04",
    title: "데이터 시각화 마스터클래스",
    teacher: "박시경",
    uni: "연세대학교",
    weeks: 14,
    learners: "12.4만",
    rating: 4.7,
    badge: "시각화",
    thumb: "python_data",
    slug: "data-visualization-master",
  },
  {
    id: "c05",
    title: "블록체인 기초부터 실무",
    teacher: "최필용희",
    uni: "한양대학교",
    weeks: 14,
    learners: "12.4만",
    rating: 4.6,
    badge: "핀테크",
    thumb: "block",
    slug: "blockchain-fundamentals",
  },
  {
    id: "c06",
    title: "신경망 및 딥러닝",
    teacher: "김○○",
    uni: "고려대학교",
    weeks: 14,
    learners: "12.4만",
    rating: 4.6,
    badge: "AI",
    thumb: "deep",
    slug: "neural-networks",
  },
  {
    id: "c07",
    title: "파이썬 및 판다스 분석 기초 과정",
    teacher: "김○○",
    uni: "OOO",
    weeks: 14,
    learners: "12.4만",
    rating: 4.6,
    badge: "데이터",
    thumb: "pandas",
    slug: "python-pandas-basics",
  },
  {
    id: "c08",
    title: "생체데이터와 인공지능의 이해",
    teacher: "박○○",
    uni: "OOO",
    weeks: 14,
    learners: "12.4만",
    rating: 4.6,
    badge: "의생명",
    thumb: "human",
    slug: "bio-data-ai",
  },
  {
    id: "c09",
    title: "작물재배 전문가 기초",
    teacher: "김○○",
    uni: "전북대학교",
    weeks: 14,
    learners: "12.4만",
    rating: 4.6,
    badge: "입문",
    thumb: "seed",
    slug: "agro-basics",
  },
];
