// src/shared/courseData.js
const courseData = [
  {
    id: 1,
    slug: "ml-advanced",
    title: "머신러닝 심화 과정",
    provider: "KAIST · 김세라",
    weeks: 14,
    studentsText: "12.4만",
    rating: 4.9,
    image: "/img/edu_pro2.png",
    badges: ["AI · 미션제출", "95% 추천"],
    tags: ["AI", "머신러닝"],
  },
  {
    id: 2,
    slug: "react-advanced",
    title: "React 고급 개발 과정",
    provider: "서울대학교 · 이명환",
    weeks: 14,
    studentsText: "9.8만",
    rating: 4.8,
    image: "/img/react.png",
    badges: ["웹프론트", "88% 완강"],
    tags: ["웹", "프론트엔드"],
  },
  {
    id: 3,
    slug: "data-viz-master",
    title: "데이터 시각화 마스터클래스",
    provider: "연세대학교 · 박시경",
    weeks: 14,
    studentsText: "6.5만",
    rating: 4.7,
    image: "/img/data.png",
    badges: ["데이터과학", "82% 배움"],
    tags: ["데이터", "시각화"],
  },
  {
    id: 4,
    slug: "blockchain-basic",
    title: "블록체인 기초부터 실무",
    provider: "한양대학교 · 최필윤회",
    weeks: 14,
    studentsText: "5.2만",
    rating: 4.6,
    image: "/img/block.png",
    badges: ["핀테크", "실무 프로젝트"],
    tags: ["블록체인", "핀테크"],
  },
  // ====== AI 추천 콘텐츠 섹션 ======
  {
    id: 5,
    slug: "py-advanced",
    title: "고급 파이썬 알고리즘",
    provider: "고급 프로그래밍 · 실전",
    weeks: 14,
    studentsText: "23,000",
    rating: 4.9,
    image: "/img/python.png",
    badges: ["AI 집계: 95%"],
    tags: ["파이썬", "알고리즘"],
  },
  {
    id: 6,
    slug: "data-science-with-pandas",
    title: "파이썬으로 데이터 과학",
    provider: "데이터 과학 · 프로젝트",
    weeks: 14,
    studentsText: "23,000",
    rating: 4.8,
    image: "/img/pyton_data.png", // 폴더에 있는 파일명 그대로 (오타 주의)
    badges: ["AI 집계: 89%"],
    tags: ["데이터", "판다스"],
  },
  {
    id: 7,
    slug: "deep-learning-nn",
    title: "신경망 및 딥러닝",
    provider: "딥러닝 · 실전",
    weeks: 14,
    studentsText: "23,000",
    rating: 4.7,
    image: "/img/deep.png",
    badges: ["AI 집계: 87%"],
    tags: ["딥러닝", "신경망"],
  },
];

export default courseData;
